# Generated by Django 5.0.7 on 2024-08-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=128, verbose_name='Марка машины')),
                ('model', models.CharField(max_length=256, verbose_name='Модель машины')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('fuel_type', models.CharField(choices=[('бензин', 'Бензин'), ('дизель', 'Дизель'), ('электричество', 'Электричество'), ('гибрид', 'Гибрид')], default='gasoline', max_length=16)),
                ('transmission', models.CharField(choices=[('механическая', 'Механическая'), ('автоматическая', 'Автоматическая'), ('вариатор', 'Вариатор'), ('робот', 'Робот')], default='gasoline', max_length=16)),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
        ),
    ]
