# Generated by Django 5.0.7 on 2024-08-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('бензин', 'Бензин'), ('дизель', 'Дизель'), ('электричество', 'Электричество'), ('гибрид', 'Гибрид')], max_length=16),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('механическая', 'Механическая'), ('автоматическая', 'Автоматическая'), ('вариатор', 'Вариатор'), ('робот', 'Робот')], max_length=16),
        ),
    ]
