# Generated by Django 5.0.7 on 2024-08-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-id'], 'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
    ]
